docs update & folder structure rationalization
epiphany-platform/central-build-system pull request #26
Opened 2021-04-28 12:50 UTC by romsok24

The changes in this PR are related to updating the documentation part of CBS 
and to simplifying the project folder structure.

2021-05-30 17:45 UTC, rafzei commented on README.md
> +You can find more information in [Comparision of CI/CD tools](https://github.com/pprach/epiphany/blob/440c276cf22d873cc91478af4777ef714c8c1642/docs/design-docs/cicd-server/comparision_cicd.md) doc.
I think we shouldn't point to any fork in our documentation. Can we move this comparison to our repo?

2021-05-31 08:35 UTC, mkyc requested changes

2021-05-31 08:35 UTC, mkyc commented on docs/CBS_quickstart.md
> +<br>
why putting HTML tags in Markdown?

2021-05-31 09:34 UTC, romsok24 commented on README.md
> +You can find more information in [Comparision of CI/CD tools](https://github.com/pprach/epiphany/blob/440c276cf22d873cc91478af4777ef714c8c1642/docs/design-docs/cicd-server/comparision_cicd.md) doc.
Ok. Will take it into discussion. Referenced in [#27](https://github.com/epiphany-platform/central-build-system/issues/27)

2021-05-31 09:35 UTC, romsok24 commented on README.md
> +You can find more information in [Comparision of CI/CD tools](https://github.com/pprach/epiphany/blob/440c276cf22d873cc91478af4777ef714c8c1642/docs/design-docs/cicd-server/comparision_cicd.md) doc.
Ok. Will take it into discussion. Referenced in [#27](https://github.com/epiphany-platform/central-build-system/issues/27)

2021-05-31 09:44 UTC, romsok24 commented on docs/CBS_quickstart.md
> +<br>
It's well explained [here](https://www.markdownguide.org/basic-syntax/#line-break-best-practices).

2021-05-31 09:44 UTC, merged