Tools folder with CBS automation solutions
epiphany-platform/central-build-system pull request #28
Opened 2021-06-02 12:13 UTC by romsok24

After a successful deployment of your CBS environment instance, administrator will most probably want to automate some of the recurrent administration routines. 
Two interesting solutions that can help with it can be now explored in the [tools directory](https://github.com/epiphany-platform/central-build-system/tree/feat/tools/tools) of this repo.

2021-06-02 13:08 UTC, mkyc requested changes

2021-06-02 13:08 UTC, mkyc commented on tools/tekton-cleaner/tekton-cleanup.yaml
> +              image: harbor.cbs.hasops.com/public/tkn:cleaner.05
is this correct?

2021-06-04 09:55 UTC, romsok24 commented on tools/k8s-cert-manager/dns-01/dnschallenge_SP_create.sh
> +JAKI_NS=cert-manager
The code was updated.  
Pls recheck.

2021-06-04 09:55 UTC, romsok24 commented on tools/tekton-cleaner/Dockerfile
> +FROM ubuntu:18.04 as posrednik
The code was updated.  
Pls recheck.

2021-06-04 09:59 UTC, romsok24 commented on tools/tekton-cleaner/tekton-cleanup.yaml
> +              image: harbor.cbs.hasops.com/public/tkn:cleaner.05
The code was updated.  
Pls recheck.

2021-06-04 14:09 UTC, mkyc approved these changes

2021-06-04 14:29 UTC, merged