Allowing environment independent build
epiphany-platform/central-build-system pull request #31
Opened 2021-06-14 10:01 UTC by romsok24

This PR is focused on updating the current code ( main branch ) in a sucha a way
that it would make it possible to build independent CBS environments, like: TST, DEV, UAT, etc...
Please note, that the current code state allows only for PROD building .

Also an emphasis was put on tagging and variable naming as it's important both for environment readability and its logical separation.
Some variables initialization scraps were moved to Azure KV so it could have be a central point of CBS initialization and configuration. 

Before going for this PR, the current branch code was successfully tested by subsequent builds of non-PROD environment.
Due to the subject code changes, these tests were completely secure and transparent to the existing PROD environment.

2021-06-14 10:46 UTC, mkyc requested changes

2021-06-14 10:46 UTC, mkyc commented on sources/core/env/terraform.tfvars
> +project_name = "your_project_name"   # will be used for naming and addressing your Azure RGs
\n

2021-06-14 10:46 UTC, mkyc commented on sources/core/env/variables.tf
> +variable "enviroment" {
Can you provide examples of that variable you'll be giving to next environments? I mean just here in comment for me to understand better this variable and difference to "project_name"

2021-06-14 10:46 UTC, mkyc commented on sources/core/env/vault.tf
>    resource_group_name = "cbs-tools-rg" //var.keyvault_rg
so does it mean that all environments would store their key vaults in one single RG? 

BTW, I do not understand comments here and one line up

2021-06-14 10:46 UTC, mkyc commented on sources/init_vnet/main.tf
> +    name                 = "cbs-${var.name}-disk"
shouldn't machine have name updated as well? Also It would be good it machine would get any tags describing her function. It's not clear here.

2021-06-14 10:46 UTC, mkyc commented on sources/core/modules/harbor/provider.tf
> -  version = "2.27.0"
why removing?

2021-06-14 10:46 UTC, mkyc commented on sources/core/modules/basic/main.tf
> +    CreatedWhen = timestamp()
```suggestion
    created = timestamp()
```

2021-06-14 10:46 UTC, mkyc commented on sources/core/modules/basic/modules/vms/main.tf
> +  name                  = "cbs-${var.name}-${var.service}-${count.index}"
```suggestion
  name                  = "cbs-${var.name}-${var.service}-${count.index}-vm"
```

2021-06-14 10:46 UTC, mkyc commented on sources/core/modules/basic/networking.tf
> +  name                 = "cbs-${var.name}-snet-${count.index}"
```suggestion
  name                 = "cbs-${var.name}-snet-${count.index}-snet"
```

2021-06-14 10:46 UTC, mkyc commented on sources/core/modules/cbsbackup/variables.tf
> +variable "domain" {
I do not see this variable being used. Am I missing something?

2021-06-14 10:46 UTC, mkyc commented on sources/core/modules/aks/main.tf
> +    CreatedWhen = timestamp()
```suggestion
    created = timestamp()
```

2021-06-14 12:52 UTC, romsok24 commented on sources/core/env/variables.tf
> +variable "enviroment" {
The "environment" and the "project_name" variables were merged into a single variable "environment".
As this decision as well as the decisions described below as an answer for the other comments have caused many code changes - the whole TST environment was build from scratch again, using the most recent code version in branch  impr/env-independent.

2021-06-14 12:54 UTC, romsok24 commented on sources/core/env/vault.tf
>    resource_group_name = "cbs-tools-rg" //var.keyvault_rg
> so does it mean that all environments would store their key vaults in one single RG?
Yes, they will.

> BTW, I do not understand comments here and one line up

These comments were kind of leftovers and I decided to clean them up.

2021-06-14 13:00 UTC, romsok24 commented on sources/init_vnet/main.tf
> +    name                 = "cbs-${var.name}-disk"
Right. The new naming policy that is reflecting the self-explanatory naming guidelines was extend here to include also the machine names.

More extensive and detailed tagging is planned to be part of the next PR coming soon. 
I didn't want to put too many changes here.

2021-06-14 13:01 UTC, romsok24 commented on sources/core/modules/harbor/provider.tf
> -  version = "2.27.0"
https://github.com/epiphany-platform/central-build-system/pull/31/commits/682d5a23084d5401b7c7243fcd5252219d4e87dd

2021-06-14 13:03 UTC, romsok24 commented on sources/core/modules/basic/main.tf
> +    CreatedWhen = timestamp()
I would rather stay with this tag as this is part of more extensive and detailed tagging code change that is planned to be part of one of the next PRs coming soon. This will include both: 'CreatedWhen' and 'CreatedBy' tags.

2021-06-14 13:04 UTC, romsok24 commented on sources/core/modules/basic/modules/vms/main.tf
> +  name                  = "cbs-${var.name}-${var.service}-${count.index}"
This suggestion was accepted and reflected in the code of the branch.

2021-06-14 13:05 UTC, romsok24 commented on sources/core/modules/basic/networking.tf
> +  name                 = "cbs-${var.name}-snet-${count.index}"
This suggestion was accepted and reflected in the code of the branch.

2021-06-14 13:05 UTC, romsok24 commented on sources/core/modules/cbsbackup/variables.tf
> +variable "domain" {
The var was removed.

2021-06-14 13:05 UTC, romsok24 commented on sources/core/modules/aks/main.tf
> +    CreatedWhen = timestamp()
I would rather stay with this tag as this is part of more extensive and detailed tagging code change that is planned to be part of one of the next PRs coming soon. This will include both: 'CreatedWhen' and 'CreatedBy' tags.

2021-06-14 13:24 UTC, mkyc commented on sources/core/modules/basic/main.tf
> +    CreatedWhen = timestamp()
Ok, but please be consistent in tags case (camelCase or PascalCase or snake_case or kebab-case everywhere) in this next PR.

2021-06-14 13:28 UTC, mkyc requested changes
One last spotted mistake.

2021-06-14 13:28 UTC, mkyc commented on sources/core/modules/basic/networking.tf
> +  name                 = "cbs-${var.name}-snet-${count.index}-snet"
```suggestion
  name                 = "cbs-${var.name}-${count.index}-snet"
```

2021-06-15 06:34 UTC, romsok24 commented on sources/core/modules/basic/networking.tf
> +  name                 = "cbs-${var.name}-snet-${count.index}-snet"
👍

2021-06-15 07:12 UTC, romsok24 commented on sources/core/modules/basic/main.tf
> +    CreatedWhen = timestamp()
👍

2021-06-15 08:08 UTC, mkyc approved these changes

2021-06-15 08:53 UTC, merged